In [1]:
import numpy as np
import pandas as pd

### 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
outcomes = [1, 2, 3, 4, 5, 6]

n_simulations = 100_000
n_trials = 2

rolls = np.random.choice(outcomes, size = (n_simulations, n_trials))
rolls

array([[2, 6],
       [5, 2],
       [3, 3],
       ...,
       [5, 5],
       [5, 4],
       [3, 1]])

In [3]:
# Since we know there are two trials, we can check that the trials in each simulation are equal to each other
def check_doubles(rolls):
    doubles_list = []
    for sim in rolls:
        doubles_list.append(sim[0] == sim[1])
        
    return doubles_list

# Boolean array if simulation is a double
doubles_sims = check_doubles(rolls)
doubles_sims

[False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 F

In [55]:
# Convert boolean list to np array and find mean for probability
print(f"The probability of doubles is:  {np.array(doubles_sims).mean() * 100}%")

The probability of doubles is:  16.541%


### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
# Heads is 1
outcomes = [0, 1]

n_simulations = 100_000
n_trials = 8

flips = np.random.choice(outcomes, size = (n_simulations, n_trials))
sum_of_flips = flips.sum(axis = 1)

In [6]:
# Probability of exactly 3 heads
prob_3_heads = (sum_of_flips == 3).mean()
print(f"The probability of flipping exactly three heads is {prob_3_heads * 100}%")

The probability of flipping exactly three heads is 21.931%


In [7]:
# Probability of more than three heads
prob_over_3_heads = (sum_of_flips > 3).mean()
print(f"The probability of flipping more than three heads is {round(prob_over_3_heads * 100, 2)}%")

The probability of flipping more than three heads is 63.55%


### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [8]:
# Data science is 1
outcomes = [0, 1]

n_simulations = 100_000
n_trials = 2

combos = np.random.choice(outcomes, size = (n_simulations, n_trials), p = [.75, .25])
combos

array([[0, 0],
       [1, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [1, 0]])

In [9]:
prob_all_data_sci = (combos.sum(axis = 1) == 2).mean()
print(f"The probability both billboards feature data science students:  {prob_all_data_sci * 100}%")

The probability both billboards feature data science students:  6.202%


### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [49]:
n_simulations = 100_000
n_trials = 5

daily_purchases = np.random.normal(loc = 3, scale = 1.5, size = (n_simulations, n_trials))
weekly_purchases = daily_purchases.sum(axis = 1)
prob_poptarts_left = (weekly_purchases < 17).mean()

print(f"There is a {round(prob_poptarts_left * 100, 2)}% chance there are poptarts left.")

[ True  True False ...  True  True  True]
There is a 72.36% chance there are poptarts left.


### 5. Compare Heights
#### * Men have an average height of 178 cm and standard deviation of 8cm.
#### * Women have a mean of 170, sd = 6cm.
#### * If a man and woman are chosen at random, P(woman taller than man)?

In [42]:
male_outcomes = np.random.normal(loc = 178, scale = 8, size = n_simulations)
female_outcomes = np.random.normal(loc = 170, scale = 6, size = n_simulations)
n_simulations = 100_000

male_simulations = np.random.choice(male_outcomes, size = n_simulations)
male_simulations

array([175.35456557, 182.6823537 , 166.79429982, ..., 179.73513815,
       165.12255508, 182.18078681])

In [43]:
female_simulations = np.random.choice(female_outcomes, size = n_simulations)
female_simulations

array([154.94791467, 186.12867023, 175.87307265, ..., 172.87807605,
       172.79784056, 160.64121851])

In [56]:
prob_taller_female = np.greater(female_simulations, male_simulations).mean()
print(f"Probability that female is taller:  {prob_taller_female * 100}%")

Probability that female is taller:  21.204%
